# Generated by Django 2.0.7 on 2018-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('zipcode', models.CharField(blank=True, max_length=15)),
                ('street', models.CharField(blank=True, max_length=250)),
                ('apartment', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
            },
        ),
    ]
